### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [kieraw/tc359-project7#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by kieraw** [comment]
It is updated now! @chrisvfritz 
--Kiera

**Comment by chrisvfritz** [comment]
Gar! It is now beyond my powers to break. :smiley: One more thing I'd like you to fix though: I see some inconsistent indentation in `app.rb` and `holidays.erb`. Can you update both of them to consistently use two-space soft-tabs? [This resource](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) may help, but if it doesn't and you're having trouble configuring your text editor, just let me know and I'll be happy to help.

**Comment by kieraw** [comment]
Fixed @chrisvfritz 
--Kiera

**Comment by chrisvfritz** [comment]
It looks like [there are still some tabs in `app.rb`](https://github.com/kieraw/tc359-project7/blob/master/app.rb#L8-L10). [This video](https://www.youtube.com/watch?v=GMf8dlrEbB4) may prove useful in more easily updating current files.

**Comment by kieraw** [comment]
@chrisvfritz should be fixed now.
--Kiera

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
